[package]
name = "dotfiles-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "5.1.0"
serde_json = "1.0.113"
walkdir = "2.4.0"
